<!-- src/routes/mana_gov/create-project-execution/+page.svelte -->
<script lang="ts">
  import { onMount } from 'svelte';
  import ProjectExecutionForm from '../components/ProjectExecutionForm.svelte';
  import '../styles.css';

  let projectPlans: { id: number; projectName: string; tasks?: { id: number }[] }[] = [];
  let loading = true;

  onMount(async () => {
    try {
      const response = await fetch('/api/project-plans');
      if (!response.ok) {
        throw new Error('Failed to fetch project plans');
      }
      projectPlans = await response.json();
    } catch (err) {
      console.error('Error fetching project plans:', err);
      projectPlans = [];
    } finally {
      loading = false;
    }
  });

  function handleProjectExecution(event: CustomEvent<{
    projectPlanId: number;
    actualManaHours: number;
  }>) {
    const projectExecution = event.detail;
    
    // Find the associated ProjectPlan to derive defaults
    const associatedProjectPlan = projectPlans.find(plan => plan.id === projectExecution.projectPlanId);

    // Derive default values for tasks and peerVotes from the associated ProjectPlan
    const fullProjectExecution = {
      ...projectExecution,
      id: Date.now(), // Replace with actual ID if generated by the backend
      projectPlanId: associatedProjectPlan?.id || projectExecution.projectPlanId,
      tasks: associatedProjectPlan?.tasks?.map(task => ({
        taskPlanId: task.id,
        actualManaHours: 0,
        status: 'NotStarted' as const,
      })) || [],
      peerVotes: [],
    };

    console.log('Project execution submitted:', fullProjectExecution);
    // Handle project execution submission (e.g., save to a database or send to an API)
  }
</script>

{#if loading}
  <div>Loading...</div>
{:else}
  <div class="create-project-execution-page">
    <header class="text-white text-xl font-bold">
      <div class="title flex-grow text-center">
        <h1 class="text-white text-xl font-bold">Create New Project Execution</h1>
      </div>
    </header>

    <section class="project-execution-form">
      <ProjectExecutionForm 
        {projectPlans}
        on:addProjectExecution={handleProjectExecution}
      />
    </section>
  </div>
{/if}
