<!-- src/routes/mana_gov/create-project-plan/+page.svelte -->
<script lang="ts">
  import { onMount } from 'svelte';
  import ProjectPlanForm from '../components/ProjectPlanForm.svelte';
  import '../styles.css';

  let proposals: { id: number; title: string; manaHoursBudgeted?: number }[] = [];
  let loading = true;

  onMount(async () => {
    try {
      const response = await fetch('/api/proposals/approved-active');
      if (!response.ok) {
        throw new Error('Failed to fetch proposals');
      }
      proposals = await response.json();
    } catch (err) {
      console.error('Error fetching proposals:', err);
      proposals = [];
    } finally {
      loading = false;
    }
  });

  function handleProjectPlan(event: CustomEvent<{
    proposalId: number;
    projectName: string;
    totalManaHours: number;
  }>) {
    const projectPlan = event.detail;
    
    // Find the associated Proposal to derive defaults
    const associatedProposal = proposals.find(proposal => proposal.id === projectPlan.proposalId);

    // Derive default values from the associated Proposal
    const fullProjectPlan = {
      ...projectPlan,
      id: Date.now(), // Replace with actual ID if generated by the backend
      proposalId: associatedProposal?.id || projectPlan.proposalId,
      votingPowerPercentage: 0,
      createdAt: new Date().toISOString(),
      updatedAt: null,
      developers: {},
      totalManaHours: associatedProposal?.manaHoursBudgeted || projectPlan.totalManaHours,
    };

    console.log('Project plan submitted:', fullProjectPlan);
    // Handle project plan submission (e.g., send it to an API or save to a database)
  }
</script>

{#if loading}
  <div>Loading...</div>
{:else}
  <div class="create-project-plan-page">
    <header class="text-white text-xl font-bold">
      <div class="title flex-grow text-center">
        <h1 class="text-white text-xl font-bold">Create New Project Plan</h1>
      </div>
    </header>

    <section class="project-plan-form">
      <ProjectPlanForm 
        {proposals}
        on:addProjectPlan={handleProjectPlan}
      />
    </section>
  </div>
{/if}
